# Generated by Django 4.2.2 on 2023-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Institute', models.CharField(max_length=100)),
                ('AcademicProgramName', models.CharField(max_length=200)),
                ('Quota', models.CharField(max_length=50)),
                ('SeatType', models.CharField(max_length=50)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('OpeningRank', models.FloatField(blank=True, null=True)),
                ('ClosingRank', models.FloatField(blank=True, null=True)),
                ('Year', models.IntegerField()),
                ('Round', models.IntegerField()),
            ],
        ),
    ]
